from airflow.models import Variable

DATALAKE_FOLDER_PATH = Variable.get('DATALAKE_FOLDER_PATH')
PROCESSING_FOLDER_PATH = Variable.get('PROCESSING_FOLDER_PATH')
PROCESSED_DATA_FOLDER_PATH = Variable.get('PROCESSED_DATA_FOLDER_PATH')

POSTGRES_DB_NAME = Variable.get('POSTGRES_DB_NAME')
POSTGRES_HOST = Variable.get('POSTGRES_HOST')
POSTGRES_PORT = Variable.get('POSTGRES_PORT')
POSTGRES_USERNAME = Variable.get('POSTGRES_USERNAME')
POSTGRES_PASSWORD = Variable.get('POSTGRES_PASSWORD')
